### PR TITLE
get_ibus_addr: fix on x11

### PR DESCRIPTION
**Pull request by symphorien**
this now returns a correct path on my machine, but I failed to use pmim on my machine. How to I set it up?

### CODE REVIEW

**Comment by secext2022** [comment]
What went wrong when you run pmim ?

**Comment by secext2022** [comment]
Thank you for your contribution !

**Comment by symphorien** [comment]
> What went wrong when you run pmim ?

when I run `cargo run` it runs fine but I don't know how to tell ibus to use it. Actually I'm not really interested in pmim, I have my own implementation of IBusEngine and I would like to know how to configure ibus to use it: what key combination should I type so that IBusEngine::process_key_event is triggered? (Note that I'm not really familiar with ibus, that may be a dumb question)

**Comment by secext2022** [comment]
See here: <https://github.com/fm-elpac/pmim-ibus/blob/main/doc/%E5%AE%89%E8%A3%85.md#21-%E9%80%82%E7%94%A8%E4%BA%8E%E5%A4%A7%E9%83%A8%E5%88%86-gnulinux-%E5%8F%91%E8%A1%8C%E7%89%88%E6%9C%AC-%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE>

----

Add a file to `/usr/share/ibus/component/pmim_ibrus.xml`:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- /usr/share/ibus/component/pmim_ibrus.xml -->
<component>
  <name>org.fm_elpac.pmim</name>
  <description>PMIM (ibus)</description>
  <exec>/path/to/ibrus</exec>
  <version>0.1.0</version>
  <author>secext2022</author>
  <license>GPL</license>
  <homepage>https://github.com/fm-elpac/pmim-ibus</homepage>
  <textdomain>pmim-ibus</textdomain>

  <engines>
    <engine>
      <name>pmim</name>
      <language>zh_CN</language>
      <license>GPL</license>
      <author>secext2022</author>
      <layout>default</layout>
      <longname>胖喵拼音</longname>
      <description>胖喵拼音输入法 (ibus)</description>
      <rank>99</rank>
      <symbol>喵</symbol>
      <icon_prop_key>InputMode</icon_prop_key>
      <textdomain>pmim-ibus</textdomain>
    </engine>
  </engines>
</component>
```

change `<exec>/path/to/ibrus</exec>` to the path of `ibrus` binary.

Then restart ibus-daemon.
Then you can add this new input method in `ibus-setup`.

----

You should not run `ibrus` directly, but switch input method with ibus.
Then `ibus-daemon` will run `ibrus` for you.

**Comment by secext2022** [comment]
When `ibus-daemon` start, it will read configuration files from `/usr/share/ibus/component/*.xml`, and register `<component>` and `<engine>` (input method).

Then switch input method with ibus, ibus will run binary as child process from `<component>` `<exec>` path.
Then ibus will send key event to the `<engine>`.

**Pull request merged**
